# Generated by Django 2.0 on 2022-09-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecs', '0002_auto_20220901_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecs',
            name='reason',
            field=models.CharField(default='', max_length=256, verbose_name='创建失败原因'),
        ),
        migrations.AddField(
            model_name='ecs',
            name='request_content',
            field=models.TextField(default='', verbose_name='调用创建虚拟机对象的请求原文'),
        ),
        migrations.AddField(
            model_name='ecs',
            name='response_content',
            field=models.TextField(default='', verbose_name='调用创建虚拟机对象的响应原文'),
        ),
        migrations.AddField(
            model_name='ecs',
            name='server_id',
            field=models.CharField(default='', max_length=32, verbose_name='目标机器的id,比如serverA serverB'),
        ),
        migrations.AddField(
            model_name='ecs',
            name='status',
            field=models.CharField(default='', max_length=32, verbose_name='创建的状态,0创建中1创建成功2创建失败'),
        ),
    ]
